# Generated by Django 5.0.6 on 2026-05-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de piezas por pedido para esta categoría'),
        ),
    ]
