# Generated by Django 6.0.4 on 2026-05-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_min_order_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(default='521XXXXXXXXXX', help_text='Número WhatsApp sin + ni espacios (ej: 5214771234567)', max_length=30)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Aparece en "Nuevos ingresos" del inicio'),
        ),
    ]
