# Generated by Django 5.0.6 on 2026-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_siteconfig_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='track_message',
            field=models.TextField(blank=True, default='', help_text='Mensaje visible para el cliente en la página de seguimiento de pedido.'),
        ),
    ]
