# Generated by Django 6.0.4 on 2026-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_volumetier_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumetier',
            name='min_qty',
            field=models.PositiveIntegerField(help_text='Cantidad mínima para activar este precio'),
        ),
    ]
