# Generated by Django 6.0.4 on 2026-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_volumetier_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de piezas totales de esta categoría por pedido'),
        ),
        migrations.AlterField(
            model_name='volumetier',
            name='min_qty',
            field=models.PositiveIntegerField(help_text='Cantidad mínima para activar el descuento'),
        ),
    ]
