# Generated by Django 6.0.4 on 2026-05-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_category_min_order_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sizes', models.JSONField()),
                ('conversion_table', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de tallas',
                'verbose_name_plural': 'Grupos de tallas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.sizegroup'),
        ),
    ]
