# Generated by Django 6.0.4 on 2026-06-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_productimage_color_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
