# Generated by Django 5.0.6 on 2026-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_variant_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_deactivated',
            field=models.BooleanField(default=False, help_text='Desactivado por reconcile_catalog (removido del proveedor). Distingue de ocultamientos manuales; habilita reactivación segura.'),
        ),
    ]
