# Generated by Django 5.0.6 on 2026-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_product_auto_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modaverse_name',
            field=models.CharField(blank=True, default='', help_text='Nombre crudo de Modaverse (productName sin _clean_name). Se usa para encontrar el producto en el carrito de Modaverse.', max_length=500),
        ),
    ]
