# Generated by Django 5.0.6 on 2026-06-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_product_modaverse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_url', models.CharField(max_length=600, unique=True)),
                ('display_name', models.CharField(max_length=500)),
                ('modaverse_name', models.CharField(blank=True, max_length=500)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Producto pendiente',
                'verbose_name_plural': 'Productos pendientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
