# Generated by Django 6.0.4 on 2026-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_pendingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproduct',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='pending/'),
        ),
    ]
