# Generated by Django 6.0.4 on 2026-06-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_pendingproduct_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Palabras clave separadas por coma. Ej: gorra,cap,ny,la,za')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo de artículo',
                'verbose_name_plural': 'Tipos de artículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Para qué clientes o promoción es este código.', max_length=200)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Monto fijo en MXN a descontar.', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('usos_max', models.PositiveIntegerField(blank=True, help_text='Máximo de usos. Dejar vacío para ilimitado.', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('valid_hasta', models.DateField(blank=True, null=True)),
                ('tipo_articulo', models.ForeignKey(blank=True, help_text='Dejar vacío para código global (aplica a cualquier artículo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos', to='catalog.tipoarticulo')),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'ordering': ['codigo'],
            },
        ),
    ]
