# Generated by Django 6.0.4 on 2026-06-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_codigodescuento_canal_categoria_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigodescuento',
            name='tipo_articulo',
            field=models.ForeignKey(blank=True, help_text='(Negocio) Dejar vacío para código global. Aplica solo a artículos del tipo seleccionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos', to='catalog.tipoarticulo'),
        ),
    ]
