# Generated by Django 5.0.6 on 2026-07-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_codigodescuento_tipo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigodescuento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, help_text='Monto en MXN. Fijo: se aplica al total. Por ítem: se multiplica por cada ítem del alcance.', max_digits=8),
        ),
    ]
