# Generated by Django 6.0.4 on 2026-07-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_codigodescuento_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo del proveedor para TODOS los productos de esta subcategoría. Vacío = usa el base_price individual de cada producto.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='profit_margin_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia para esta subcategoría. Vacío = usa la ganancia de la categoría raíz.', max_digits=8, null=True),
        ),
    ]
