# Generated by Django 6.0.4 on 2026-08-12 22:32

from django.db import migrations, models
from django.db.models import F


def marcar_precios_existentes_como_automaticos(apps, schema_editor):
    """Declara que el precio que hay hoy en BD es el del proveedor.

    Sin este backfill la marca queda en NULL y la sincronización no puede
    distinguir un precio congelado de uno editado a mano, así que no tocaría
    ninguno — y los precios viejos (el bug que originó este campo) seguirían
    ahí. A partir de acá, toda divergencia entre base_price y modaverse_price
    es una edición manual y se respeta.
    """
    apps.get_model('catalog', 'Product').objects.update(modaverse_price=F('base_price'))


def limpiar_marcas(apps, schema_editor):
    apps.get_model('catalog', 'Product').objects.update(modaverse_price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_category_base_price_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modaverse_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último precio del proveedor. Si difiere de base_price, el precio fue editado a mano.', max_digits=8, null=True),
        ),
        migrations.RunPython(
            marcar_precios_existentes_como_automaticos,
            limpiar_marcas,
        ),
    ]
