# Generated by Django 6.0.4 on 2026-08-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_product_modaverse_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Texto tal como se teclea. Se guarda en minúsculas y con espacios colapsados.', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='catalog.tipoarticulo')),
            ],
            options={
                'verbose_name': 'Alias de texto',
                'verbose_name_plural': 'Alias de texto',
                'ordering': ['texto'],
            },
        ),
    ]
