# Generated by Django 6.0.4 on 2026-10-04 03:30

from django.db import migrations, models
from django.utils import timezone


def marcar_ocultos(apps, schema_editor):
    # Antes de este campo no se sabía desde cuándo estaba oculto cada uno:
    # el reloj de los ya ocultos empieza al aplicar la migración.
    Product = apps.get_model('catalog', 'Product')
    Product.objects.filter(is_active=False).update(hidden_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_aliastexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se ocultó (is_active pasó a False). Vacío si está activo.', null=True),
        ),
        migrations.RunPython(marcar_ocultos, migrations.RunPython.noop),
    ]
