# Generated by Django 5.0.6 on 2026-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_savedcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
