# Generated by Django 6.0.4 on 2026-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_backfill_order_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Cuándo el staff vio este pedido en el panel (marca global, no por usuario).', null=True),
        ),
    ]
