# Generated by Django 6.0.4 on 2026-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='URL de rastreo que manda el proveedor (17track, etc). Obligatoria para pasar a Enviado.', max_length=500),
        ),
    ]
