# Generated by Django 6.0.4 on 2026-06-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('tienda', 'Tienda física')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='negocio.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
