# Generated by Django 6.0.4 on 2026-06-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('tienda', 'Tienda física'), ('bot', 'Bot')], default='whatsapp', max_length=20),
        ),
    ]
