# Generated by Django 6.0.4 on 2026-06-29 19:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_tipo_articulo_codigo_descuento'),
        ('negocio', '0006_add_bot_origen_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aplicados', to='catalog.codigodescuento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
