# Generated by Django 6.0.4 on 2026-07-22 20:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_pedido_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Con signo: + suma a la caja, − resta.', max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, help_text='Saldo de caja que quedó tras aplicar este ajuste.', max_digits=12)),
                ('motivo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de caja',
                'verbose_name_plural': 'Ajustes de caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
