# Generated by Django 6.0.4 on 2026-09-18 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0008_ajustecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustecaja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
