# Generated by Django 6.0.4 on 2026-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0009_fecha_default_localdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idem_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
